<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'login',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:57',
                'parent_id' => 45,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'logout',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'register',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'password.request',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'password.email',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'password.reset',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'password.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'home',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-08-22 05:16:43',
                'parent_id' => 0,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'role.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'role.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'role.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'role.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'role.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'role.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'role.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'permission.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'permission.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'permission.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'permission.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'permission.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'permission.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'permission.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'permission.add',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'permission.addmenu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'user.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 25,
                'icon' => NULL,
                'isURL' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'user.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 26,
                'icon' => NULL,
                'isURL' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'user.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 27,
                'icon' => NULL,
                'isURL' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'user.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 28,
                'icon' => NULL,
                'isURL' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'user.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 29,
                'icon' => NULL,
                'isURL' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'user.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 30,
                'icon' => NULL,
                'isURL' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'user.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 31,
                'icon' => NULL,
                'isURL' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'assignrole.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 32,
                'icon' => NULL,
                'isURL' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'assignrole.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 33,
                'icon' => NULL,
                'isURL' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'assignrole.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 34,
                'icon' => NULL,
                'isURL' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'assignrole.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 35,
                'icon' => NULL,
                'isURL' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'assignrole.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 36,
                'icon' => NULL,
                'isURL' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'assignrole.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 37,
                'icon' => NULL,
                'isURL' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'assignrole.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 38,
                'icon' => NULL,
                'isURL' => 1,
            ),
            38 => 
            array (
                'id' => 45,
                'name' => '#always',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:14:01',
                'updated_at' => '2019-08-22 05:16:43',
                'parent_id' => 0,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 0,
            ),
            39 => 
            array (
                'id' => 46,
                'name' => '#usermanagement',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 09:25:56',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 8,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 0,
            ),
            40 => 
            array (
                'id' => 47,
                'name' => 'menu-index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            41 => 
            array (
                'id' => 48,
                'name' => 'menu-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            42 => 
            array (
                'id' => 49,
                'name' => 'menu-build-menu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            43 => 
            array (
                'id' => 50,
                'name' => 'menu-delete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            44 => 
            array (
                'id' => 51,
                'name' => 'menu-search',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            45 => 
            array (
                'id' => 52,
                'name' => 'display-name-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            46 => 
            array (
                'id' => 81,
                'name' => 'category.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:31',
                'parent_id' => 0,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            47 => 
            array (
                'id' => 82,
                'name' => 'category.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:31',
                'parent_id' => 81,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            48 => 
            array (
                'id' => 83,
                'name' => 'category.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:31',
                'parent_id' => 81,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            49 => 
            array (
                'id' => 84,
                'name' => 'category.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:31',
                'parent_id' => 81,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            50 => 
            array (
                'id' => 85,
                'name' => 'category.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:31',
                'parent_id' => 81,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            51 => 
            array (
                'id' => 86,
                'name' => 'category.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 81,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            52 => 
            array (
                'id' => 87,
                'name' => 'category.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 81,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            53 => 
            array (
                'id' => 88,
                'name' => 'client.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 0,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            54 => 
            array (
                'id' => 89,
                'name' => 'client.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 88,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            55 => 
            array (
                'id' => 90,
                'name' => 'client.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 88,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            56 => 
            array (
                'id' => 91,
                'name' => 'client.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 88,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            57 => 
            array (
                'id' => 92,
                'name' => 'client.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 88,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            58 => 
            array (
                'id' => 93,
                'name' => 'client.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 88,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            59 => 
            array (
                'id' => 94,
                'name' => 'client.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 05:07:57',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 88,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            60 => 
            array (
                'id' => 95,
                'name' => 'servicetype.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 0,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            61 => 
            array (
                'id' => 96,
                'name' => 'servicetype.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 95,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            62 => 
            array (
                'id' => 97,
                'name' => 'servicetype.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 95,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            63 => 
            array (
                'id' => 98,
                'name' => 'servicetype.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 95,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            64 => 
            array (
                'id' => 99,
                'name' => 'servicetype.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 95,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            65 => 
            array (
                'id' => 100,
                'name' => 'servicetype.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-28 09:53:59',
                'parent_id' => 95,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            66 => 
            array (
                'id' => 101,
                'name' => 'servicetype.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-16 06:21:41',
                'updated_at' => '2019-08-28 09:53:59',
                'parent_id' => 95,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            67 => 
            array (
                'id' => 102,
                'name' => 'service.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:39',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 0,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            68 => 
            array (
                'id' => 103,
                'name' => 'service.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:40',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 102,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            69 => 
            array (
                'id' => 104,
                'name' => 'service.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:40',
                'updated_at' => '2019-08-20 05:33:32',
                'parent_id' => 102,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            70 => 
            array (
                'id' => 105,
                'name' => 'service.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:40',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            71 => 
            array (
                'id' => 106,
                'name' => 'service.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:40',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            72 => 
            array (
                'id' => 107,
                'name' => 'service.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:40',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            73 => 
            array (
                'id' => 108,
                'name' => 'service.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-07-17 05:19:40',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            74 => 
            array (
                'id' => 109,
                'name' => 'category.phone',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 05:30:23',
                'updated_at' => '2019-08-20 05:33:33',
                'parent_id' => 0,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            75 => 
            array (
                'id' => 110,
                'name' => 'category.sendSMS',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 05:30:23',
                'updated_at' => '2019-08-20 05:33:33',
                'parent_id' => 0,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            76 => 
            array (
                'id' => 111,
                'name' => 'service.invoice',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 05:30:23',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            77 => 
            array (
                'id' => 112,
                'name' => 'quotation.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 05:30:23',
                'updated_at' => '2019-08-22 05:16:43',
                'parent_id' => 0,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            78 => 
            array (
                'id' => 113,
                'name' => 'quotation.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 05:30:23',
                'updated_at' => '2019-08-20 05:33:33',
                'parent_id' => 112,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            79 => 
            array (
                'id' => 114,
                'name' => 'quotation.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 05:30:23',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            80 => 
            array (
                'id' => 115,
                'name' => 'quotation.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 06:08:42',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            81 => 
            array (
                'id' => 116,
                'name' => 'quotation.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 06:08:42',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            82 => 
            array (
                'id' => 117,
                'name' => 'quotation.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 06:08:42',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
            83 => 
            array (
                'id' => 118,
                'name' => 'quotation.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 06:08:42',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            84 => 
            array (
                'id' => 119,
                'name' => 'quotation.invoice',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-20 09:35:31',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            85 => 
            array (
                'id' => 120,
                'name' => 'quotation.finalized',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-21 10:10:38',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            86 => 
            array (
                'id' => 121,
                'name' => '#quotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-21 10:13:04',
                'updated_at' => '2019-08-22 05:16:43',
                'parent_id' => 0,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 0,
            ),
            87 => 
            array (
                'id' => 123,
                'name' => 'quotation.showbyquotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-22 07:04:03',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            88 => 
            array (
                'id' => 124,
                'name' => 'quotation.addquotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-22 08:20:34',
                'updated_at' => '2019-08-22 08:20:50',
                'parent_id' => 112,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            89 => 
            array (
                'id' => 125,
                'name' => 'quotation.savequotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-22 08:20:34',
                'updated_at' => '2019-08-22 08:20:50',
                'parent_id' => 112,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            90 => 
            array (
                'id' => 126,
                'name' => 'quotation.groupinvoice',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-23 09:17:17',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            91 => 
            array (
                'id' => 127,
                'name' => 'quotation.updatequotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-26 04:45:49',
                'updated_at' => '2019-08-26 04:46:02',
                'parent_id' => 112,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            92 => 
            array (
                'id' => 128,
                'name' => 'quotation.bulkedit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-26 06:34:23',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            93 => 
            array (
                'id' => 129,
                'name' => 'quotation.bulkupdate',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-26 08:21:53',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            94 => 
            array (
                'id' => 130,
                'name' => 'quotation.addtoservices',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-27 04:38:29',
                'updated_at' => '2019-08-28 04:53:49',
                'parent_id' => 112,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            95 => 
            array (
                'id' => 131,
                'name' => 'quotation.storetoservices',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-27 04:38:29',
                'updated_at' => '2019-08-28 04:53:49',
                'parent_id' => 112,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            96 => 
            array (
                'id' => 132,
                'name' => 'quotation.finalizedquotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-27 09:55:31',
                'updated_at' => '2019-08-28 04:53:49',
                'parent_id' => 112,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            97 => 
            array (
                'id' => 133,
                'name' => 'quotation.showfinalizedquotation',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-28 04:53:34',
                'updated_at' => '2019-08-28 04:53:49',
                'parent_id' => 112,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            98 => 
            array (
                'id' => 134,
                'name' => 'service.bulkinvoice',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-28 09:32:31',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            99 => 
            array (
                'id' => 135,
                'name' => 'service.bulkedit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-08-28 09:52:31',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            100 => 
            array (
                'id' => 136,
                'name' => 'service.bulkupdate',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-03 04:27:27',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            101 => 
            array (
                'id' => 137,
                'name' => 'service.addservice',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-03 04:27:27',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            102 => 
            array (
                'id' => 138,
                'name' => 'service.saveservice',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-03 04:27:27',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            103 => 
            array (
                'id' => 139,
                'name' => 'service.bulkdelete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-03 04:27:27',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            104 => 
            array (
                'id' => 140,
                'name' => 'service.pdf',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-03 04:27:27',
                'updated_at' => '2019-09-03 04:28:15',
                'parent_id' => 102,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            105 => 
            array (
                'id' => 141,
                'name' => 'quotation.bulkdelete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-03 04:27:27',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            106 => 
            array (
                'id' => 142,
                'name' => 'quotation.bulkeditfinalized',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-05 04:25:17',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            107 => 
            array (
                'id' => 143,
                'name' => 'quotation.bulkupdatefinalized',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-05 04:25:17',
                'updated_at' => '2019-09-05 04:25:34',
                'parent_id' => 112,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            108 => 
            array (
                'id' => 144,
                'name' => 'quotation.pdf',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-09-25 06:15:07',
                'updated_at' => '2019-09-25 06:15:20',
                'parent_id' => 112,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
        ));
        
        
    }
}